pipeline:
  build:
    image: ubuntu
    commands:
      - apt update
      - apt install -y nodejs
      - apt install -y lsb-release
      - lsb_release -r
      - echo "muahahahah"
  ssh:
      image: appleboy/drone-ssh
      host: 163.172.140.121
      username: root
      password: donotspamme
      port: 22
      script:
        - echo hello
        - echo world
        - apt update
        - apt upgrade -y
        - lsb_release -r
