pipeline:
#  build:
#    image: ubuntu
#    commands:
#      - apt update
#      - apt install -y nodejs
#      - apt install -y lsb-release
#      - lsb_release -r
#      - echo "muahahahah"
  ssh:
      image: appleboy/drone-ssh
      host: e08c1aa4-08e4-4028-a057-811ddb38a712.pub.cloud.scaleway.com
      username: root
      password: "donotspamme"
      port: 22
      script:
        - echo hello
        - echo world
        - apt update
        - apt upgrade -y
        - lsb_release -r
