sed -i.back '/null/d' $1
sed -i.back 's/}/},/g' $1
sed -i.back 's/time/"time"/g' $1
sed -i.back 's/ch1/"ch1"/g' $1
sed -i.back 's/ch2/"ch2"/g' $1
sed -i.back 's/ch3/"ch3"/g' $1
sed -i.back 's/ch5/"ch5"/g' $1
sed -i.back 's/ch6/"ch6"/g' $1
sed -i.back 's/ch7/"ch7"/g' $1
sed -i.back 's/raw_current/"raw_current"/g' $1
